import { Data } from "@/structs/classes/Data";

/// Only used as input
export class RegisterStruct {
    /// Username
    email: string;

    /// Password
    password: string;

    /**
     * Public key of the user, generated by the client. The client can decide to create a new key. Probably once a year.
     * For administrators, this key needs to get signed by the organization in order to be valid. This signature will get validated by
     * normal users when they need to encrypt data using the public key of administrators
     */
    publicKey: string;

    static decode(data: Data): RegisterStruct {
        const struct = new RegisterStruct();
        struct.email = data.field("email").string;
        struct.password = data.field("password").string;
        struct.publicKey = data.field("publicKey").key;

        return struct;
    }
}
