import { Data } from "@stamhoofd-common/encoding/src/classes/Data";
import EmailDecoder from "@stamhoofd-common/encoding/src/structs/EmailDecoder";

/// Only used as input
export class RegisterStruct {
    /// Username
    email: string;

    /// Password
    password: string;

    /**
     * Public key of the user, generated by the client. The client can decide to create a new key. Probably once a year.
     * For administrators, this key needs to get signed by the organization in order to be valid. This signature will get validated by
     * normal users when they need to encrypt data using the public key of administrators
     */
    publicKey: string;

    /**
     * Optional. The signature of the public key when creating administrators. This will get verified immediately. If verification fails, it won't get saved to the database without any notification (brute force protection)
     */
    adminSignature?: string;

    static decode(data: Data): RegisterStruct {
        const struct = new RegisterStruct();
        struct.email = data.field("email").decode(EmailDecoder);
        struct.password = data.field("password").string;
        struct.publicKey = data.field("publicKey").key;
        struct.adminSignature = data.optionalField("adminSignature")?.string;

        return struct;
    }
}
