version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # in case you don't want to enable version updates
    allow:
      # Allow updates for production dependencies only
      - dependency-type: "production"