allowBuilds:
  ttf2woff2: true
  '@parcel/watcher': true
  argon2: true
  core-js: true
  esbuild: true
  nx: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

linkWorkspacePackages: true

packages:
  - 'frontend/app/*'
  - 'frontend/shared/*'
  - 'backend/app/*'
  - 'backend/shared/*'
  - 'shared/*'
  - 'tests/*'
  - '.development/*'
