settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: auth
    path: auth
    commands:
      generate:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
        - ../protos/stamhoofd/auth.proto
        - ../protos/stamhoofd/email.proto
  - name: email
    path: email
    commands:
      generate:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
        - ../protos/stamhoofd/email.proto
