-- The GTP index (Gezond Toekomst Perspectief).
--
--     GTP waarden / (Omkaderingscijfer * 2)
--
-- A unit ideally scores 100 or more. The scale only says something up to roughly 150 members.
--
-- Reads from a `gtp_basis` CTE aliased `gb`, which supplies `gtp_waarden` (see `gtp-waarden.sql`)
-- alongside the kinderen and leiding the omkaderingscijfer divides -- unrounded, so the rounding of
-- the number on screen does not move the index.
--
-- A unit without leiding has no omkaderingscijfer and therefore no index, which the NULLIF keeps
-- null rather than turning into a zero the charts would draw.
ROUND(gb.gtp_waarden / NULLIF(2 * (gb.kinderen / NULLIF(gb.leiding, 0)), 0), 2)
