// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email/service/email.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6152eddc6b864c5d, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SendUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendUserRequest) Reset()         { *m = SendUserRequest{} }
func (m *SendUserRequest) String() string { return proto.CompactTextString(m) }
func (*SendUserRequest) ProtoMessage()    {}
func (*SendUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6152eddc6b864c5d, []int{1}
}

func (m *SendUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendUserRequest.Unmarshal(m, b)
}
func (m *SendUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendUserRequest.Marshal(b, m, deterministic)
}
func (m *SendUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendUserRequest.Merge(m, src)
}
func (m *SendUserRequest) XXX_Size() int {
	return xxx_messageInfo_SendUserRequest.Size(m)
}
func (m *SendUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendUserRequest proto.InternalMessageInfo

func (m *SendUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendUserRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendUserRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "be.stamhoofd.backend.email.SendRequest")
	proto.RegisterType((*SendUserRequest)(nil), "be.stamhoofd.backend.email.SendUserRequest")
}

func init() { proto.RegisterFile("email/service/email.proto", fileDescriptor_6152eddc6b864c5d) }

var fileDescriptor_6152eddc6b864c5d = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0xac, 0xad, 0x8e, 0x68, 0x61, 0x0e, 0x1a, 0xe3, 0x45, 0x72, 0x51, 0x10, 0x26,
	0xa0, 0x6f, 0x20, 0xf4, 0x50, 0x3c, 0x59, 0x11, 0xc4, 0x8b, 0x64, 0xb3, 0xd3, 0x1a, 0x6d, 0x3a,
	0x35, 0xbb, 0x11, 0xfa, 0x40, 0xbe, 0xa7, 0xec, 0xd6, 0x85, 0x7a, 0x08, 0xd2, 0xdb, 0xfe, 0xc3,
	0xbf, 0xdf, 0xee, 0xc7, 0xc0, 0x19, 0xd7, 0x45, 0x35, 0xcf, 0x0d, 0x37, 0x5f, 0x55, 0xc9, 0xb9,
	0x4f, 0xb4, 0x6c, 0xc4, 0x0a, 0xa6, 0x8a, 0xc9, 0xd8, 0xa2, 0x7e, 0x13, 0x99, 0x6a, 0x52, 0x45,
	0xf9, 0xc1, 0x0b, 0x4d, 0xbe, 0x91, 0x9e, 0xcf, 0x44, 0x66, 0x73, 0xce, 0x7d, 0x53, 0xb5, 0xd3,
	0x9c, 0xeb, 0xa5, 0x5d, 0xad, 0x2f, 0x66, 0xf7, 0x70, 0xf8, 0xc8, 0x0b, 0x3d, 0xe1, 0xcf, 0x96,
	0x8d, 0xc5, 0x63, 0x88, 0xad, 0x24, 0xd1, 0x45, 0x74, 0x75, 0x30, 0x89, 0xad, 0x60, 0x02, 0x03,
	0xd3, 0xaa, 0x77, 0x2e, 0x6d, 0x12, 0xfb, 0x61, 0x88, 0x88, 0xd0, 0x53, 0xa2, 0x57, 0xc9, 0xae,
	0x1f, 0xfb, 0x73, 0xf6, 0x0c, 0x43, 0x07, 0x7b, 0x32, 0xdc, 0x04, 0xe0, 0x29, 0x0c, 0x5a, 0xc3,
	0xcd, 0x6b, 0xa5, 0x7f, 0xa9, 0x7d, 0x17, 0xc7, 0x7a, 0x3b, 0xf2, 0xcd, 0x77, 0x04, 0x7b, 0x23,
	0x67, 0x83, 0x63, 0xe8, 0xb9, 0x37, 0xf0, 0x92, 0xba, 0x95, 0x69, 0x43, 0x29, 0x3d, 0xa1, 0xb5,
	0x3f, 0x05, 0x7f, 0x1a, 0x39, 0xff, 0x6c, 0x07, 0x1f, 0x60, 0x3f, 0x7c, 0x17, 0xaf, 0xff, 0xc3,
	0x6d, 0x48, 0x75, 0x23, 0xef, 0x86, 0x2f, 0x47, 0x7f, 0x96, 0xa4, 0xfa, 0xbe, 0x72, 0xfb, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x57, 0xa6, 0x89, 0xa6, 0xbc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	// Send an email to a specific email address.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Send an email to a specific user id.
	SendUser(ctx context.Context, in *SendUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/be.stamhoofd.backend.email.Email/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SendUser(ctx context.Context, in *SendUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/be.stamhoofd.backend.email.Email/SendUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	// Send an email to a specific email address.
	Send(context.Context, *SendRequest) (*empty.Empty, error)
	// Send an email to a specific user id.
	SendUser(context.Context, *SendUserRequest) (*empty.Empty, error)
}

// UnimplementedEmailServer can be embedded to have forward compatible implementations.
type UnimplementedEmailServer struct {
}

func (*UnimplementedEmailServer) Send(ctx context.Context, req *SendRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedEmailServer) SendUser(ctx context.Context, req *SendUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUser not implemented")
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/be.stamhoofd.backend.email.Email/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SendUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/be.stamhoofd.backend.email.Email/SendUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendUser(ctx, req.(*SendUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "be.stamhoofd.backend.email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Email_Send_Handler,
		},
		{
			MethodName: "SendUser",
			Handler:    _Email_SendUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email/service/email.proto",
}
