import { DocumentTemplateLogger } from './DocumentTemplateLogger.js';
import { EmailAddressLogger } from './EmailAddressLogger.js';
import { EmailLogger } from './EmailLogger.js';
import { EmailTemplateLogger } from './EmailTemplateLogger.js';
import { EventLogger } from './EventLogger.js';
import { GroupLogger } from './GroupLogger.js';
import { MemberLogger } from './MemberLogger.js';
import { MemberPlatformMembershipLogger } from './MemberPlatformMembershipLogger.js';
import { MemberResponsibilityRecordLogger } from './MemberResponsibilityRecordLogger.js';
import { OrderLogger } from './OrderLogger.js';
import { OrganizationLogger } from './OrganizationLogger.js';
import { OrganizationRegistrationPeriodLogger } from './OrganizationRegistrationPeriodLogger.js';
import { PaymentLogger } from './PaymentLogger.js';
import { PlatformLogger } from './PlatformLogger.js';
import { RegistrationLogger } from './RegistrationLogger.js';
import { RegistrationPeriodLogger } from './RegistrationPeriodLogger.js';
import { StripeAccountLogger } from './StripeAccountLogger.js';
import { UserLogger } from './UserLogger.js';
import { WebshopLogger } from './WebshopLogger.js';
import { modelLogDefinitions } from '../services/AuditLogService.js';

modelLogDefinitions.set(RegistrationLogger.model, RegistrationLogger);
modelLogDefinitions.set(GroupLogger.model, GroupLogger);
modelLogDefinitions.set(OrganizationLogger.model, OrganizationLogger);
modelLogDefinitions.set(PlatformLogger.model, PlatformLogger);
modelLogDefinitions.set(EventLogger.model, EventLogger);
modelLogDefinitions.set(RegistrationPeriodLogger.model, RegistrationPeriodLogger);
modelLogDefinitions.set(OrganizationRegistrationPeriodLogger.model, OrganizationRegistrationPeriodLogger);
modelLogDefinitions.set(StripeAccountLogger.model, StripeAccountLogger);
modelLogDefinitions.set(MemberLogger.model, MemberLogger);
modelLogDefinitions.set(WebshopLogger.model, WebshopLogger);
modelLogDefinitions.set(OrderLogger.model, OrderLogger);
modelLogDefinitions.set(PaymentLogger.model, PaymentLogger);
modelLogDefinitions.set(MemberPlatformMembershipLogger.model, MemberPlatformMembershipLogger);
modelLogDefinitions.set(MemberResponsibilityRecordLogger.model, MemberResponsibilityRecordLogger);
modelLogDefinitions.set(DocumentTemplateLogger.model, DocumentTemplateLogger);
modelLogDefinitions.set(EmailLogger.model, EmailLogger);
modelLogDefinitions.set(EmailTemplateLogger.model, EmailTemplateLogger);
modelLogDefinitions.set(EmailAddressLogger.model, EmailAddressLogger);
modelLogDefinitions.set(UserLogger.model, UserLogger);
