SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `users`
ADD COLUMN `memberId` varchar(36) NULL AFTER `id`;
ALTER TABLE `users` ADD FOREIGN KEY (`memberId`) REFERENCES `members` (`id`) ON UPDATE CASCADE ON DELETE SET NULL;
SET FOREIGN_KEY_CHECKS=1;
