SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `groups`
ADD COLUMN `waitingListId` varchar(36) NULL AFTER `defaultAgeGroupId`;
ALTER TABLE `groups` ADD FOREIGN KEY (`waitingListId`) REFERENCES `groups` (`id`) ON UPDATE CASCADE ON DELETE SET NULL;
SET FOREIGN_KEY_CHECKS=1;
