CREATE TABLE `event_notifications` (
    `id` varchar(36) NOT NULL DEFAULT '',
    `typeId` varchar(36) NOT NULL,
    `startDate` datetime NOT NULL,
    `endDate` datetime NOT NULL,
    `status` varchar(36) NOT NULL,
    `feedbackText` text NULL,
    `organizationId` varchar(36) DEFAULT NULL,
    `recordAnswers` json NOT NULL DEFAULT ('{"value": {}, "version": 0}'),
    `createdBy` varchar(36) DEFAULT NULL,
    `submittedBy` varchar(36) DEFAULT NULL,
    `createdAt` datetime NOT NULL,
    `updatedAt` datetime NOT NULL,
    PRIMARY KEY (`id`),
    KEY `organizationId` (`organizationId`),
    KEY `createdBy` (`createdBy`),
    KEY `submittedBy` (`submittedBy`),
    KEY `startDate` (`startDate`) USING BTREE,
    CONSTRAINT `organizationId` FOREIGN KEY (`organizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `createdBy` FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `submittedBy` FOREIGN KEY (`submittedBy`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
