CREATE TABLE `invoiced_balance_items` (
  `id` varchar(36) NOT NULL,
  `organizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `invoiceId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `balanceItemId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `balanceInvoicedAmount` int NOT NULL,
  `quantity` int NOT NULL,
  `unitPrice` int NOT NULL,
  `VATPercentage` int NOT NULL,
  `VATIncluded` tinyint(1) NOT NULL,
  `VATExcempt` varchar(36) DEFAULT NULL,
  `totalWithoutVAT` int NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `organizationId` (`organizationId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `balanceItemId` (`balanceItemId`),
  CONSTRAINT `invoiced_balance_items_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `invoiced_balance_items_ibfk_2` FOREIGN KEY (`invoiceId`) REFERENCES `invoices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `invoiced_balance_items_ibfk_3` FOREIGN KEY (`balanceItemId`) REFERENCES `balance_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
