CREATE TABLE `invoices` (
  `id` varchar(36) NOT NULL,
  `number` varchar(36) DEFAULT NULL,
  `customer` json NOT NULL,
  `seller` json NOT NULL,
  `organizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `payingOrganizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `payableRoundingAmount` int NOT NULL,
  `VATTotal` json NOT NULL,
  `VATTotalAmount` int NOT NULL,
  `totalWithoutVAT` int NOT NULL,
  `totalBalanceInvoicedAmount` int NOT NULL,
  `totalWithVAT` int NOT NULL,
  `ipAddress` varchar(36) DEFAULT NULL,
  `userAgent` varchar(36) DEFAULT NULL,
  `stripeAccountId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `reference` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `pdf` json DEFAULT NULL,
  `xml` json DEFAULT NULL,
  `negativeInvoiceId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `didSendPeppol` tinyint(1) NOT NULL DEFAULT '0',
  `invoicedAt` datetime DEFAULT NULL,
  `dueAt` datetime DEFAULT NULL,
  `updatedAt` datetime NOT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `number` (`organizationId`,`number`) USING BTREE,
  KEY `negativeInvoiceId` (`negativeInvoiceId`),
  KEY `payingOrganizationId` (`payingOrganizationId`),
  CONSTRAINT `invoices_ibfk_1` FOREIGN KEY (`negativeInvoiceId`) REFERENCES `invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoices_ibfk_2` FOREIGN KEY (`organizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `invoices_ibfk_3` FOREIGN KEY (`payingOrganizationId`) REFERENCES `organizations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
