CREATE TABLE `settlements` (
  `id` varchar(36) NOT NULL,
  `provider` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `externalId` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `stripeAccountId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `organizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `reference` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `amount` bigint NOT NULL DEFAULT '0',
  `currency` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'EUR',
  `status` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `settledAt` datetime NOT NULL,
  `syncedAt` datetime DEFAULT NULL,
  `syncFailureCount` int NOT NULL DEFAULT '0',
  `unexplainedAmount` bigint NOT NULL DEFAULT '0',
  `transactionCount` int NOT NULL DEFAULT '0',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `providerExternalId` (`provider`,`externalId`),
  KEY `stripeAccountId` (`stripeAccountId`),
  KEY `organizationId` (`organizationId`),
  KEY `syncedAt` (`syncedAt`),
  KEY `settledAt` (`settledAt`),
  KEY `unexplainedAmount` (`unexplainedAmount`),
  CONSTRAINT `settlements_ibfk_1` FOREIGN KEY (`stripeAccountId`) REFERENCES `stripe_accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `settlements_ibfk_2` FOREIGN KEY (`organizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
