CREATE TABLE `application_fees` (
  `id` varchar(36) NOT NULL,
  `externalId` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `type` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `amount` bigint NOT NULL DEFAULT '0',
  `organizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `payingOrganizationId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `payingStripeAccountId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `payingPaymentId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `settlementChargeId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `settlementId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `balanceItemId` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `occurredAt` datetime NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `externalIdType` (`externalId`,`type`),
  UNIQUE KEY `settlementChargeId` (`settlementChargeId`),
  KEY `organizationId` (`organizationId`),
  KEY `payingOrganizationId` (`payingOrganizationId`),
  KEY `payingStripeAccountId` (`payingStripeAccountId`),
  KEY `payingPaymentId` (`payingPaymentId`),
  KEY `settlementId` (`settlementId`),
  KEY `balanceItemId` (`balanceItemId`),
  KEY `occurredAt` (`occurredAt`),
  CONSTRAINT `application_fees_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_2` FOREIGN KEY (`payingOrganizationId`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_3` FOREIGN KEY (`payingStripeAccountId`) REFERENCES `stripe_accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_4` FOREIGN KEY (`payingPaymentId`) REFERENCES `payments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_5` FOREIGN KEY (`settlementChargeId`) REFERENCES `settlement_charges` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_6` FOREIGN KEY (`settlementId`) REFERENCES `settlements` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `application_fees_ibfk_7` FOREIGN KEY (`balanceItemId`) REFERENCES `balance_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
