export {default as RecordsConfigurationView} from './RecordsConfigurationView.vue'
export {default as EditRecordCategoryView} from './EditRecordCategoryView.vue'
export {default as RecordCategoryRow} from './components/RecordCategoryRow.vue'
export {default as ViewRecordCategoryAnswersBox} from './components/ViewRecordCategoryAnswersBox.vue'
export * from './RecordEditorSettings'
