vars:
  VERSION:
  APP_ID:
  APP_NAME:
  HOSTNAME:

platforms:
  android:
    versionName: $VERSION
    appName: $APP_NAME
    incrementVersionCode: true
    packageName: $APP_ID

  ios:
    targets:
      App:
        version: $VERSION
        displayName: $APP_NAME
        bundleId: $APP_ID
        incrementBuild: true

        builds:
          Debug:
            entitlements:
              replace: true
              entries:
                - com.apple.developer.associated-domains: ['webcredentials:dashboard.stamhoofd?mode=developer', 'webcredentials:$HOSTNAME?mode=developer', 'applinks:$HOSTNAME?mode=developer']

          Release:
            entitlements:
              replace: true
              entries:
                - com.apple.developer.associated-domains: ['webcredentials:$HOSTNAME', 'applinks:$HOSTNAME']
