vars:
  VERSION:
  APP_ID:
  APP_NAME:
  HOSTNAME:

platforms:
  android:
    versionName: $VERSION
    appName: $APP_NAME
    incrementVersionCode: true
    packageName: $APP_ID

  ios:
    targets:
      App:
        version: $VERSION
        bundleId: $APP_ID
        incrementBuild: true
